const categoriesWomen = [
  {
    id: 1,
    category: "T-Shirts",
    products: [
      {
        name: "Cotton Logo Tee",
        image:
          "https://img.freepik.com/premium-photo/brooch-form-lady-hat-white-blouse-brunette-girl-young-woman-posing-yellow-background-sunlight-shadow-studio_115318-6832.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Soft cotton blend with front logo graphic.",
        price: 749,
        sale: true,
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Oversized Graphic Tee",
        image:
          "https://img.freepik.com/premium-photo/t-shirt-mockup_1132451-344.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Relaxed fit with a bold statement print.",
        price: 899,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Striped Casual Tee",
        image:
          "https://img.freepik.com/premium-psd/woman-standing-posing-photoshoot_53876-27917.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Classic stripes for everyday comfort.",
        price: 699,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 2,
    category: "Dress",
    products: [
      {
        name: "Floral Midi Dress",
        image:
          "https://img.freepik.com/free-photo/beautiful-young-woman-wearing-fashionable-clothes-walking-down-street_839833-3813.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Elegant floral dress perfect for day outs.",
        price: 1599,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Evening Gown",
        image:
          "https://img.freepik.com/free-photo/beautiful-girl-standing-long-black-dress-near-seaside-daytime_176474-2914.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Chic and graceful for special occasions.",
        price: 2999,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Casual Shirt Dress",
        image:
          "https://img.freepik.com/free-photo/beautiful-woman_1328-1290.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Laid-back look for casual settings.",
        price: 1199,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 3,
    category: "Jeans",
    products: [
      {
        name: "High-Rise Skinny Jeans",
        image:
          "https://img.freepik.com/free-photo/stylish-woman-road_23-2147732012.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Classic high-rise fit with stretch.",
        price: 1799,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Mom Fit Jeans",
        image:
          "https://img.freepik.com/free-photo/young-woman-with-skateboard_23-2148937871.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Comfortable fit with retro vibes.",
        price: 1999,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Ripped Boyfriend Jeans",
        image:
          "https://img.freepik.com/free-photo/stylish-young-woman-black-cap-standing-front-restaurant_23-2148148148.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Stylish with distressed details.",
        price: 1899,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 4,
    category: "Leggings",
    products: [
      {
        name: "High-Waist Black Leggings",
        image:
          "https://img.freepik.com/free-photo/woman-sportswear-exercising-outdoors_23-2148965007.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Stretchy and versatile for all-day wear.",
        price: 899,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Printed Activewear Leggings",
        image:
          "https://img.freepik.com/free-photo/pretty-fitness-girl-putting-effort-into-exercising-using-heavy-dumbbells-side-view-confident_7502-10539.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Breathable with bold patterns.",
        price: 1099,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Yoga Fit Leggings",
        image:
          "https://img.freepik.com/premium-photo/smile-woman-morning-routine-yoga-mat-warm-up-training-balance-floor-house-sportswear-athlete-ready-exercise-pilates-wellness-with-workout-person_590464-419586.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Perfect for gym and studio sessions.",
        price: 999,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 5,
    category: "Lehnga",
    products: [
      {
        name: "Traditional Red Lehenga",
        image:
          "https://img.freepik.com/premium-photo/woman-red-dress-with-gold-tassle-front_1298691-26843.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Graceful ethnic wear with golden embroidery.",
        price: 6999,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Pastel Floral Lehenga",
        image:
          "https://img.freepik.com/premium-photo/woman-pink-dress-with-palm-tree-background_1113980-2406.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Modern twist on classic design.",
        price: 7999,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Mirror Work Lehenga",
        image:
          "https://img.freepik.com/premium-photo/bridal-lehenga-coli-creative-shoot_1012351-11.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Bright and elegant for festive vibes.",
        price: 8499,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 6,
    category: "Top",
    products: [
      {
        name: "Ruffle Sleeve Top",
        image:
          "https://img.freepik.com/premium-photo/beautiful-indian-woman-with-wavy-hair-against-white-wall_251136-54239.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Flowy and feminine top with ruffled sleeves.",
        price: 649,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Basic Cotton Crop Top",
        image:
          "https://img.freepik.com/free-photo/cute-blonde-girl-posing-front-ferris-wheel_23-2148648175.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Perfect for layering or summer wear.",
        price: 499,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Chiffon Printed Blouse",
        image:
          "https://img.freepik.com/free-photo/flamenca-holding-manila-shawl-looking-down_23-2148235346.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Lightweight with stylish patterns.",
        price: 899,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 7,
    category: "Sleepware",
    products: [
      {
        name: "Cotton Night Suit",
        image:
          "https://img.freepik.com/free-photo/young-beautiful-woman-blue-pajamas-sitting-bed-resting-enjoying-weekend-happy-positive-smiling-cheerfully-bedroom-interior_141793-102491.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Soft and breathable cotton fabric.",
        price: 1199,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Satin Pajama Set",
        image:
          "https://img.freepik.com/premium-photo/woman-studio-stands-large-white-window-blue-negligee_1048944-27038644.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Silky-smooth feel for ultimate comfort.",
        price: 1499,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Printed Lounge Set",
        image:
          "https://img.freepik.com/free-photo/future-mother-drinking-cup-tea-sitting-bed_8353-5127.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Stylish and cozy for lazy days.",
        price: 999,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 8,
    category: "Skirts",
    products: [
      {
        name: "Pleated Midi Skirt",
        image:
          "https://img.freepik.com/free-photo/smiling-beautiful-elegant-woman-posing-camera_259150-58979.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Elegant and flowy for all seasons.",
        price: 999,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Denim Mini Skirt",
        image:
          "https://img.freepik.com/free-photo/park-walking-talking-fancy-flirty-success_1303-2994.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Classic blue wash with button closure.",
        price: 899,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Floral Wrap Skirt",
        image:
          "https://img.freepik.com/free-photo/caucasian-standing-front-modern-building-pink-dress-hairband_181624-58091.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Wrap style with vibrant print.",
        price: 799,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 9,
    category: "Shorts",
    products: [
      {
        name: "Denim High Waist Shorts",
        image:
          "https://img.freepik.com/free-photo/long-shot-woman-standing-basketball-field_23-2148286141.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Trendy and comfortable for summer.",
        price: 849,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Athleisure Running Shorts",
        image:
          "https://img.freepik.com/free-photo/summer-lifestyle-fashion-portrait-young-stylish-hipster-woman-walking-street_1153-6690.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Moisture-wicking with stretch waistband.",
        price: 599,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cotton Lounge Shorts",
        image:
          "https://img.freepik.com/premium-photo/woman-wears-red-top-crop-with-white-shorts-trendy-girl-outfit_782515-2357.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Relaxed fit with side pockets.",
        price: 499,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 10,
    category: "Saree",
    products: [
      {
        name: "Silk Zari Saree",
        image:
          "https://img.freepik.com/free-photo/portrait-young-woman-wearing-tradition-sari-garment_52683-90221.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Traditional silk with golden zari work.",
        price: 4999,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Georgette Printed Saree",
        image:
          "https://img.freepik.com/premium-photo/woman-sari-stands-front-wall-with-floral-print_1298309-40764.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Lightweight and perfect for casual wear.",
        price: 1599,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Chiffon Party Wear Saree",
        image:
          "https://img.freepik.com/premium-photo/beautiful-indian-girl-red-saree_872233-678.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Elegant with sequin details.",
        price: 2499,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 11,
    category: "Jump Suits",
    products: [
      {
        name: "Denim Utility Jumpsuit",
        image:
          "https://img.freepik.com/free-photo/full-height-attractive-beautiful-woman-wearing-overalls-with-sunglasses-smiling-with-happy-joyful-isolated_231208-5609.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "All-in-one casual comfort outfit.",
        price: 1999,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Printed Wide-Leg Jumpsuit",
        image:
          "https://img.freepik.com/premium-photo/stylish-women039s-clothing-looks-spectacular-girl-casual-clothes-street-fashion-fashion-acces_954205-559.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Floral print with relaxed silhouette.",
        price: 1699,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Satin Evening Jumpsuit",
        image:
          "https://img.freepik.com/free-photo/pretty-woman-wearing-black-suit-hair-bun-makeup-smiling-posing-standing-near-gates-outdoor-hand-waist-looking-down-stylish-fashion_343629-84.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Chic and elegant with back zip.",
        price: 2299,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 12,
    category: "Ethnic Sets",
    products: [
      {
        name: "Kurta Palazzo Set",
        image:
          "https://img.freepik.com/premium-photo/woman-blue-dress-stands-front-building_919955-58837.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Cotton blend with embroidered detailing.",
        price: 1799,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Anarkali Suit Set",
        image:
          "https://img.freepik.com/free-photo/beautiful-young-woman-wearing-sari_23-2149502970.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Flared style with dupatta included.",
        price: 2299,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Printed Straight Set",
        image:
          "https://img.freepik.com/free-photo/woman-dress_1303-3764.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Perfect blend of tradition and comfort.",
        price: 1499,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
];

export { categoriesWomen };
