const categoriesMan = [
  {
    id: 1,
    category: "T-Shirts",
    products: [
      {
        name: "Logo-Graphic Crew Neck Tee",
        image:
          "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTEdZ38AB7lrZ_Qgob7vaZ9h8qr5yb1b4Xj3DBQqnM3VF4G6NlMu_Yex8RB2Ow7vTLCcfs867YsQvT1xlk6xVLJXcFP22ny_hB2gh22dHw72RFlKezt_pSrKg",
        description: "Soft cotton blend with front logo graphic.",
        price: 749,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Vintage Oversized Graphic Tee",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzs6fnscWN4XRsMGbdwecpVCBDonwc6hgpxu78UdT6qu_q44dx_Ipn9HMwgtN8nd3MzPyZPPuy8gNwuVayhewd8IxBkQ0klnDKLHemtB8DMrkgjJVzhXr3",
        description: "Relaxed-fit tee with vintage-style graphics.",
        price: 899,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Striped V-Neck Tee",
        image:
          "https://images.meesho.com/images/products/375137834/75tbn_1200.jpg",
        description: "Soft fabric V-neck with subtle stripes.",
        price: 599,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 2,
    category: "Shirts",
    products: [
      {
        name: "Royal Blue Slim Fit Formal Shirt",
        image:
          "https://tenaxtees.com/cdn/shop/files/FLTTSS_HHHHMISP_CC5.png?v=1744203159",
        description: "Crisp blue linen shirt, slim tailored fit.",
        price: 4500,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Classic Linen Casual Shirt",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS-V1dJJ5KTF9lK53E480Q3uGTMLkFTnV9jkocdFJ4xN2UxYuvjZ_HSMBw9UXku3p5bQZIWnscksLSSw0KlYqx5RUB-a3_IkIRrIWah0cuiR6AAIPgnfHOa4Q",
        description: "Breathable linen casual button-down.",
        price: 2899,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Checkered Slim Shirt",
        image:
          "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQxSiNXKzen2O52zK1g3IOqMSHvIOv0RP-tDs1edOLkTzIYIsEMK5DRFcdg8oLVw_5zeKMP7fMB0mVRbNpELGmf5i7TY0tU3f6-Ox0yV-4",
        description: "Lightweight linen blend checkered shirt.",
        price: 3199,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 3,
    category: "Jeans",
    products: [
      {
        name: "Classic Blue Denim Jeans",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRD9GtDKEfi8aGJgzxckGwUUQ4PWL9ZHA7i_h9FKlAfJItGvLlM_NIFDwGLb7Ahw6PmYn3reskMuGESBkBZfUvN6owj1kg-VGIan0QNulk",
        description: "Timeless straight-leg blue denim.",
        price: 4999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Ripped Skinny Stretch Jeans",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTjTvbxckCoc2JezTlovX9gr3stDygTjYsIO0DggYscb6G2G2JjUwFLNMcWD2JBOP7b7xi40FUhhQIi3ABFGDAMS48bA6EoDDwbZgqxSo9T41vaS-jBr0YLQtU",
        description: "Stretch skinny jeans with rip details.",
        price: 4299,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Black Slim Fit Denim",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRdVUFvpvY_5lhWoS97SycRARV4IcAZ-1ht3ENNzLeZc4vwXaINsFqXmB4y-UakJOpJ2_mi2pUiWSWUPnBnu1S-6ukOy73SCgtAjaGz0AIhEiN3JnmGyNLkpQ",
        description: "Sleek black slim-fit denim jeans.",
        price: 4599,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },

  {
    id: 4,
    category: "Trousers",
    products: [
      {
        name: "Formal Flat-Front Trousers",
        image:
          "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRcXlgsbHta9kQOVla2mlWXvpp4wJQWEMqbsBdQomVDi7jorw0HGxzGbL3tynDTSTTA7ewpNJLHbazzGEIZg8HhmhekrXvM5ACkldAjcpI",
        description: "Tailored flat-front trousers ideal for office wear.",
        price: 3999,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Slim Fit Chinos",
        image:
          "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQi_ZvvqTHlbZIDfI1yWOJjTdC5SWMRz-eFcM5EBSAJQd5sBnO6tdO7XHNavNdayoB0FFI9c0FDmr4G4YGY1Lj_r9g4ybfUpdDV6yJJEIPs",
        description: "Versatile slim chinos for smart-casual use.",
        price: 3599,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cargo Utility Trousers",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSLNHAMSW-A1QVAgh7qK44uv86ur3KtrtBrRQ5IqnbKEVD1MabKCJ0mCq978M13W5M6HflCaz_UH0wSyvHhsT9_EZb43tQvVy4wt98UZjfSMK3LE-hfM63Z",
        description: "Functional trousers with handy cargo pockets.",
        price: 3799,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 5,
    category: "Joggers",
    products: [
      {
        name: "Sporty Performance Joggers",
        image:
          "https://img.freepik.com/free-photo/male-athlete-doing-fitness-training-workout-outside-gym_1328-4746.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Performance joggers perfect for workouts.",
        price: 2499,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Basic Black Joggers",
        image:
          "http://img.freepik.com/premium-photo/blank-black-mens-sport-sweatpants-mockup-gray-background_981499-2937.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Everyday soft-cotton black joggers.",
        price: 2199,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cuffed Fit Joggers",
        image:
          "https://img.freepik.com/premium-photo/young-fashion-mans-legs-with-white-sneakers-white-shoes_281858-2178.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Cuffed ankles with urban style.",
        price: 2699,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 6,
    category: "Shorts",
    products: [
      {
        name: "Denim Shorts",
        image:
          "https://img.freepik.com/premium-photo/young-latin-man-nature_313999-748.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Rugged style high-rise denim shorts.",
        price: 1799,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cotton Lounge Shorts",
        image:
          "https://img.freepik.com/free-photo/young-stylish-man-looking-window_23-2147862575.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Soft cotton shorts for lounging.",
        price: 1599,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cargo Utility Shorts",
        image:
          "https://img.freepik.com/premium-photo/portrait-man-with-sunglasses-nature_38810-8907.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Outdoor-ready shorts with cargo pockets.",
        price: 1999,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 7,
    category: "Blazers",
    products: [
      {
        name: "Navy Blue Meeting Blazer",
        image:
          "https://img.freepik.com/premium-photo/young-handsome-businessman-wearing-suit_220507-604.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Polished look for formal settings.",
        price: 6999,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Grey Checked Blazer",
        image:
          "https://img.freepik.com/free-photo/stylish-young-man-arranging-jacket_23-2148316607.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Stylish pattern for sleek outfits.",
        price: 7299,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Black Slim Fit Blazer",
        image:
          "https://img.freepik.com/free-photo/confident-young-man-walking-european-city-street_158595-4725.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Evening-ready slim silhouette.",
        price: 7499,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 8,
    category: "Jackets",
    products: [
      {
        name: "Urban Bomber Jacket",
        image:
          "https://img.freepik.com/free-photo/portrait-young-peson-with-their-frinds_23-2149290136.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Zip-up jacket with modern edge.",
        price: 5499,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Denim Jacket",
        image:
          "https://img.freepik.com/free-photo/man-portrait_1296-629.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Timeless rugged denim outerwear.",
        price: 5299,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Puffer Winter Jacket",
        image:
          "https://img.freepik.com/free-photo/young-attractive-male-posing-nature_181624-46384.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Warm down-filled winter coat.",
        price: 6499,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 9,
    category: "Hoodies",
    products: [
      {
        name: "Classic Pullover Hoodie",
        image:
          "https://img.freepik.com/premium-photo/vertical-shot-model-portrait-walking_755989-141.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Soft fleece hoodie with kangaroo pocket.",
        price: 2999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Zip-Up Lightweight Hoodie",
        image:
          "https://img.freepik.com/free-photo/medium-shot-contemplative-man-seaside_23-2150531603.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Perfect layering for mild days.",
        price: 2799,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Graphic Streetwear Hoodie",
        image:
          "https://img.freepik.com/premium-photo/man-with-hood-obscuring-his-face-touching-white-wall-stock-photo_195114-63322.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Bold print for urban style.",
        price: 3199,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 10,
    category: "Sweaters",
    products: [
      {
        name: "Cable-Knit Crew Sweater",
        image:
          "https://img.freepik.com/free-photo/medium-shot-smiley-man-wearing-warm-clothes_23-2149248883.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Cozy cable knit in soft wool blend.",
        price: 3999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "V-Neck Merino Sweater",
        image:
          "https://img.freepik.com/free-photo/fashionable-man-winter-knitted-clothes_158595-4105.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Smart lightweight layering piece.",
        price: 3699,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Quarter-Zip Pullover",
        image:
          "https://img.freepik.com/free-photo/young-man-enjoying-his-life-offline_23-2149295256.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Casual zip neck for comfort days.",
        price: 3899,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 11,
    category: "Ethnic Wear",
    products: [
      {
        name: "Embroidered Kurta Set",
        image:
          "https://img.freepik.com/premium-photo/man-red-dress-stands-front-green-background_278224-229.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Festive kurta with intricate embroidery.",
        price: 4599,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Silk Printed Kurta",
        image:
          "https://img.freepik.com/premium-photo/mens-designer-kurta-pajama_764575-3010.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Elegant silk print for celebrations.",
        price: 5299,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cotton Pathani Kurta",
        image:
          "https://img.freepik.com/premium-photo/man-black-dress-stands-front-green-background_278224-240.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Breathable cotton kurta for comfort.",
        price: 3999,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 12,
    category: "Nehru Jackets",
    products: [
      {
        name: "Silk Nehru Jacket",
        image:
          "https://img.freepik.com/free-photo/indian-man-traditional-attire-temple_23-2151996324.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Formal silk jacket in classic cut.",
        price: 6199,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cotton Nehru Waistcoat",
        image:
          "https://img.freepik.com/free-photo/indian-man-mountains-male-traditional-turban-hinduist_1157-41078.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Lightweight and versatile waistcoat.",
        price: 4899,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Velvet Nehru Jacket",
        image:
          "https://img.freepik.com/premium-photo/young-indian-man-traditional-wear_621325-1729.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Premium velvet ideal for weddings.",
        price: 6999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 13,
    category: "Innerwear",
    products: [
      {
        name: "Cotton Boxers Pack",
        image:
          "https://img.freepik.com/premium-photo/medical-concept-man-looking-something-boxers-closeup_392895-372532.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Pack of 3 breathable cotton boxers.",
        price: 1199,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Seamless Vests",
        image:
          "https://img.freepik.com/free-photo/portrait-fitness-young-man-standing-track-field_23-2148162072.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Soft seamless vests for daily wear.",
        price: 899,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Thermal Shorts",
        image:
          "https://img.freepik.com/free-photo/full-shot-man-experiencing-cold-exposure-wellness_23-2151138495.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Warm lightweight thermals.",
        price: 1499,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 14,
    category: "Sleepwear",
    products: [
      {
        name: "Cotton Pajama Set",
        image:
          "https://img.freepik.com/free-photo/man-gray-pajamas-comfy-sleepwear-apparel-full-body_53876-126947.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Soft pajamas with relaxed fit.",
        price: 1799,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Silk Nightshirt",
        image:
          "https://img.freepik.com/free-photo/portrait-man-eating-food-morning-breakfast-sitting-kitchen-counter_23-2148195294.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Luxurious silk nightshirt.",
        price: 2499,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Thermal Pyjama Set",
        image:
          "https://img.freepik.com/premium-photo/morning-zen-pajamaclad-man-meditates-bed_1074916-21487.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Warm thermals for chilly nights.",
        price: 1999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 15,
    category: "Footwear",
    products: [
      {
        name: "Casual Sneakers",
        image:
          "https://img.freepik.com/premium-photo/men-s-comfortable-shoes-with-natural-material-men-s-sneakers-style-kezhual-every-day-made-with-natural-leather-high-quality-photo_173815-17038.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Everyday canvas sneakers.",
        price: 2499,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Leather Loafers",
        image:
          "https://img.freepik.com/free-photo/crop-legs-businessman-near-road_23-2147932400.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Smart formal loafers in leather.",
        price: 3999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Sport Sandals",
        image:
          "https://img.freepik.com/premium-photo/footwear-fashion-photoshoot_905179-175.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Comfortable sandals for outings.",
        price: 1999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 16,
    category: "Formal Wear",
    products: [
      {
        name: "Three-Piece Suit",
        image:
          "https://img.freepik.com/free-photo/portrait-happy-smiling-young-businessman-blue-suit-isolated-white-wall_231208-9205.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Complete three-piece suit set.",
        price: 14999,
        sale: true,
        oldPrice: 800,
        discount: "25%",
        bestSeller: true,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Tailored Tuxedo",
        image:
          "https://img.freepik.com/free-photo/man-suit-studio_1303-5857.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Elegant tuxedo for black-tie events.",
        price: 17999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Formal Waistcoat",
        image:
          "https://img.freepik.com/premium-photo/elegant-man-bowtie-grizzled-man-formalwear-tux-man-bridegroom_474717-74544.jpg?uid=R154341588&ga=GA1.1.1986206314.1749443184&semt=ais_hybrid&w=740",
        description: "Classic waistcoat to complement suits.",
        price: 4999,
        sale: false,
        oldPrice: 800,
        discount: "25%",
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        quantity: 1,
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
];

export { categoriesMan };
