const categoriesKids = [
  {
    id: 1,
    category: "T-Shirts",
    products: [
      {
        name: "Cartoon Crew Neck Tee",
        image:
          "https://assets.ajio.com/medias/sys_master/root/20231020/hFZt/65325840afa4cf41f5545930/-473Wx593H-466732199-multi-MODEL.jpg",
        description: "Soft cotton tee with fun cartoon characters.",
        price: 499,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Striped Half Sleeve Tee",
        image: "https://m.media-amazon.com/images/I/61UV2SFvGcL._SL1280_.jpg",
        description: "Casual striped T-shirt for daily wear.",
        price: 399,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Color Splash Tee",
        image:
          "https://m.media-amazon.com/images/I/51WKgaHuUsL._AC_UY1100_.jpg",
        description: "Vibrant splash-print T-shirt for a bold look.",
        price: 449,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 2,
    category: "Dress",
    products: [
      {
        name: "Floral Summer Dress",
        image:
          "https://i.etsystatic.com/17194929/r/il/d0b22b/2997595857/il_570xN.2997595857_ma9h.jpg",
        description: "Breezy dress with floral patterns.",
        price: 899,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Polka Dot Party Dress",
        image:
          "https://www.glassslipperformals.com/cdn/shop/files/K38147-2-640x960.jpg?v=1692737514",
        description: "Chic polka dot dress for special days.",
        price: 999,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Pleated Pink Dress",
        image:
          "https://liandli.in/cdn/shop/files/LIFG70_3_97adac01-48ef-44dd-b8b7-11b099e431db_600x.jpg?v=1694779549",
        description: "Elegant pleated design with bow detail.",
        price: 1099,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 3,
    category: "Frok",
    products: [
      {
        name: "Denim Frock",
        image: "https://m.media-amazon.com/images/I/51BUXKRrcsL._UY1100_.jpg",
        description: "Classic denim frock with front buttons.",
        price: 1049,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Ruffled Sleeve Frock",
        image:
          "https://inayahfashion.com/cdn/shop/files/WhatsApp-Image-2024-02-07-at-10.01.13-AM-6.jpg?v=1741612224&width=990",
        description: "Stylish frock with ruffled shoulder design.",
        price: 949,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Printed Cotton Frock",
        image:
          "https://images.meesho.com/images/products/94481184/zkmqd_512.webp",
        description: "Light and soft printed cotton frock.",
        price: 849,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 4,
    category: "Jacket",
    products: [
      {
        name: "Teddy Hoodie Jacket",
        image:
          "https://ae01.alicdn.com/kf/S269291cc6d5b460dbb13211fbe075c7df.jpg_960x960.jpg",
        description: "Fuzzy hoodie jacket with bear ears.",
        price: 1299,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Puffer Zip Jacket",
        image:
          "https://img.tatacliq.com/images/i20//437Wx649H/MP000000023830859_437Wx649H_202409251219531.jpeg",
        description: "Warm and stylish winter puffer jacket.",
        price: 1399,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Rainproof Windbreaker",
        image:
          "https://contents.mediadecathlon.com/p2515719/k$47e6a5ed73834c7c4897c43d6ed2b537/picture.jpg?format=auto&f=3000x0",
        description: "Lightweight jacket with water resistance.",
        price: 1199,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 5,
    category: "Jump Suits",
    products: [
      {
        name: "Floral Ethnic Jumpsuit",
        image:
          "https://www.fayonkids.com/cdn/shop/files/manufactured-by-fayon-kids-noida-u-p-pink-bandhej-jumpsuit-41701813289216.png?v=1730174879&width=533",
        description: "Traditional design with a modern twist.",
        price: 999,
        sale: true,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Playtime Jumpsuit",
        image:
          "https://i.pinimg.com/736x/60/d8/9d/60d89d07bee40f02c5b3afbb4a5bbb3b.jpg",
        description: "Comfortable jumpsuit for active kids.",
        price: 849,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Belted Party Jumpsuit",
        image:
          "https://i.pinimg.com/736x/99/bf/69/99bf69fc9f308b0d06012fe3287eb373.jpg",
        description: "Stylish jumpsuit with a matching belt.",
        price: 1099,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 6,
    category: "Kids Coat",
    products: [
      {
        name: "Camel Wool Coat",
        image:
          "https://i.etsystatic.com/11463421/r/il/3be984/2060513220/il_fullxfull.2060513220_ckzg.jpg",
        description: "Warm wool coat in classic camel color.",
        price: 1449,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Checkered Overcoat",
        image:
          "https://kidsonthemoon.com/wp-content/uploads/2021/02/plaszcz-ruby-plaid-6-800x1120.jpg",
        description: "Trendy checkered design for winter.",
        price: 1299,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Double Breasted Coat",
        image:
          "https://i.pinimg.com/736x/0f/5a/ba/0f5aba2d9bc39d5dc340b217412e129d.jpg",
        description: "Formal coat for stylish young ones.",
        price: 1499,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 7,
    category: "Sleep Wear",
    products: [
      {
        name: "Star Pajama Set",
        image:
          "https://thisisunfolded.com/cdn/shop/products/Mira-PJ_s-Lifestyle-05.jpg?v=1667951769&width=1600",
        description: "Comfy pajamas with glow-in-the-dark stars.",
        price: 699,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cloudy Night Suit",
        image: "https://m.media-amazon.com/images/I/816W9wz4F9L._UY1100_.jpg",
        description: "Soft sleepwear with cloud and moon patterns.",
        price: 749,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cartoon Print Sleep Set",
        image:
          "https://club96.in/cdn/shop/files/BlackandWhiteTeddyBearPrintedStripedBoysNightsuit-Club96-1.jpg?v=1727177789&width=533",
        description: "Fun and soft printed nightwear for kids.",
        price: 799,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 8,
    category: "Party Dress",
    products: [
      {
        name: "Sequin Princess Gown",
        image:
          "https://lagorii.com/cdn/shop/files/17_8534f6a5-45b7-42c9-a80b-b3c52fc4dfb7.jpg?v=1730120932",
        description: "Glittery gown for special celebrations.",
        price: 1599,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Tulle Net Dress",
        image:
          "https://lagorii.com/cdn/shop/files/1_9_0015ac55-a78b-4f5f-be06-e50c540daff9.jpg?v=1718462899",
        description: "Light pink tulle party dress with bow.",
        price: 1399,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Shimmer Fairy Dress",
        image:
          "https://i.etsystatic.com/8816264/r/il/b3c128/4118285724/il_570xN.4118285724_49p0.jpg",
        description: "Fairy-style dress with glittery shimmer.",
        price: 1499,
        sale: false,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
  {
    id: 9,
    category: "Shorts",
    products: [
      {
        name: "Blue Striped Shorts",
        image:
          "https://image.hm.com/assets/hm/01/f9/01f9a447ed17af596636146a26c36c5c6c53b5ac.jpg?imwidth=2160",
        description: "Comfortable cotton shorts with stripes.",
        price: 349,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Animal Patch Shorts",
        image:
          "https://i.pinimg.com/736x/7c/e7/b2/7ce7b2a4182b26d30262dd11945ff9a0.jpg",
        description: "Fun shorts with animal patch details.",
        price: 399,
        sale: false,
        bestSeller: true,

        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
      {
        name: "Cargo Style Shorts",
        image:
          "https://www.gapcanada.ca/webcontent/0055/191/342/cn55191342.jpg",
        description: "Casual cargo shorts with extra pockets.",
        price: 449,
        sale: true,
        bestSeller: false,
        color: "White",
        availableSizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        stock: 25,
        review: 120,
        type: "Cotton",
        quantity: 1,
        length: "Standard",
        style: "Classic",
        ocatype: "Casual",
        Care: "The garment can be machine washed at mild setting, or even hand washed. Use regular home laundry detergent like Surf Excel, Tide etc. Avoid additives such as fabric softener, optical brighteners etc. Avoid scrubbing. Tumble dry at low heat or dry in shade.",
        weight: "500gm",
        genericnam: "jeans",
        manufacturer: "Unwind Minds Private Limited",
        origin: "India",
      },
    ],
  },
];

export { categoriesKids };
