const categoriesMan = [
  {
    id: 1,
    category: "T-Shirts",
    products: [
      {
        name: "Logo-Graphic Crew Neck Tee",
        image:
          "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTEdZ38AB7lrZ_Qgob7vaZ9h8qr5yb1b4Xj3DBQqnM3VF4G6NlMu_Yex8RB2Ow7vTLCcfs867YsQvT1xlk6xVLJXcFP22ny_hB2gh22dHw72RFlKezt_pSrKg",
        description: "Soft cotton blend with front logo graphic.",
        price: 749,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Vintage Oversized Graphic Tee",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzs6fnscWN4XRsMGbdwecpVCBDonwc6hgpxu78UdT6qu_q44dx_Ipn9HMwgtN8nd3MzPyZPPuy8gNwuVayhewd8IxBkQ0klnDKLHemtB8DMrkgjJVzhXr3",
        description: "Relaxed-fit tee with vintage-style graphics.",
        price: 899,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Striped V-Neck Tee",
        image:
          "https://images.meesho.com/images/products/375137834/75tbn_1200.jpg",
        description: "Soft fabric V-neck with subtle stripes.",
        price: 599,
        sale: true,
        bestSeller: false,
      },
    ],
  },
  {
    id: 2,
    category: "Shirts",
    products: [
      {
        name: "Royal Blue Slim Fit Formal Shirt",
        image:
          "https://tenaxtees.com/cdn/shop/files/FLTTSS_HHHHMISP_CC5.png?v=1744203159",
        description: "Crisp blue linen shirt, slim tailored fit.",
        price: 4500,
        sale: true,
        bestSeller: false,
      },
      {
        name: "Classic Linen Casual Shirt",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS-V1dJJ5KTF9lK53E480Q3uGTMLkFTnV9jkocdFJ4xN2UxYuvjZ_HSMBw9UXku3p5bQZIWnscksLSSw0KlYqx5RUB-a3_IkIRrIWah0cuiR6AAIPgnfHOa4Q",
        description: "Breathable linen casual button-down.",
        price: 2899,
        sale: false,
        bestSeller: true,
      },
      {
        name: "Checkered Slim Shirt",
        image:
          "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQxSiNXKzen2O52zK1g3IOqMSHvIOv0RP-tDs1edOLkTzIYIsEMK5DRFcdg8oLVw_5zeKMP7fMB0mVRbNpELGmf5i7TY0tU3f6-Ox0yV-4",
        description: "Lightweight linen blend checkered shirt.",
        price: 3199,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 3,
    category: "Jeans",
    products: [
      {
        name: "Classic Blue Denim Jeans",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRD9GtDKEfi8aGJgzxckGwUUQ4PWL9ZHA7i_h9FKlAfJItGvLlM_NIFDwGLb7Ahw6PmYn3reskMuGESBkBZfUvN6owj1kg-VGIan0QNulk",
        description: "Timeless straight-leg blue denim.",
        price: 4999,
        sale: false,
        bestSeller: true,
      },
      {
        name: "Ripped Skinny Stretch Jeans",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTjTvbxckCoc2JezTlovX9gr3stDygTjYsIO0DggYscb6G2G2JjUwFLNMcWD2JBOP7b7xi40FUhhQIi3ABFGDAMS48bA6EoDDwbZgqxSo9T41vaS-jBr0YLQtU",
        description: "Stretch skinny jeans with rip details.",
        price: 4299,
        sale: true,
        bestSeller: false,
      },
      {
        name: "Black Slim Fit Denim",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRdVUFvpvY_5lhWoS97SycRARV4IcAZ-1ht3ENNzLeZc4vwXaINsFqXmB4y-UakJOpJ2_mi2pUiWSWUPnBnu1S-6ukOy73SCgtAjaGz0AIhEiN3JnmGyNLkpQ",
        description: "Sleek black slim-fit denim jeans.",
        price: 4599,
        sale: false,
        bestSeller: false,
      },
    ],
  },

  {
    id: 4,
    category: "Trousers",
    products: [
      {
        name: "Formal Flat-Front Trousers",
        image:
          "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRcXlgsbHta9kQOVla2mlWXvpp4wJQWEMqbsBdQomVDi7jorw0HGxzGbL3tynDTSTTA7ewpNJLHbazzGEIZg8HhmhekrXvM5ACkldAjcpI",
        description: "Tailored flat-front trousers ideal for office wear.",
        price: 3999,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Slim Fit Chinos",
        image:
          "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQi_ZvvqTHlbZIDfI1yWOJjTdC5SWMRz-eFcM5EBSAJQd5sBnO6tdO7XHNavNdayoB0FFI9c0FDmr4G4YGY1Lj_r9g4ybfUpdDV6yJJEIPs",
        description: "Versatile slim chinos for smart-casual use.",
        price: 3599,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Cargo Utility Trousers",
        image:
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSLNHAMSW-A1QVAgh7qK44uv86ur3KtrtBrRQ5IqnbKEVD1MabKCJ0mCq978M13W5M6HflCaz_UH0wSyvHhsT9_EZb43tQvVy4wt98UZjfSMK3LE-hfM63Z",
        description: "Functional trousers with handy cargo pockets.",
        price: 3799,
        sale: true,
        bestSeller: false,
      },
    ],
  },
  {
    id: 5,
    category: "Joggers",
    products: [
      {
        name: "Sporty Performance Joggers",
        image: "https://cdn.shopify.com/s/files/example11.jpg",
        description: "Performance joggers perfect for workouts.",
        price: 2499,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Basic Black Joggers",
        image: "https://some-retailer.com/images/joggers-basic.jpg",
        description: "Everyday soft-cotton black joggers.",
        price: 2199,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Cuffed Fit Joggers",
        image: "https://images.evereve.com/example-short.jpg",
        description: "Cuffed ankles with urban style.",
        price: 2699,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 6,
    category: "Shorts",
    products: [
      {
        name: "Denim Shorts",
        image: "https://vervetdenim.com/cdn/example-denim.jpg",
        description: "Rugged style high-rise denim shorts.",
        price: 1799,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Cotton Lounge Shorts",
        image: "https://gapfactory.com/cdn/example-cotton-short.jpg",
        description: "Soft cotton shorts for lounging.",
        price: 1599,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Cargo Utility Shorts",
        image: "https://roxy.com/cdn/example-short2.jpg",
        description: "Outdoor-ready shorts with cargo pockets.",
        price: 1999,
        sale: true,
        bestSeller: false,
      },
    ],
  },
  {
    id: 7,
    category: "Blazers",
    products: [
      {
        name: "Navy Blue Meeting Blazer",
        image: "https://example.com/images/blazers/navy.jpg",
        description: "Polished look for formal settings.",
        price: 6999,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Grey Checked Blazer",
        image: "https://example.com/images/blazers/grey-check.jpg",
        description: "Stylish pattern for sleek outfits.",
        price: 7299,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Black Slim Fit Blazer",
        image: "https://example.com/images/blazers/black-slim.jpg",
        description: "Evening-ready slim silhouette.",
        price: 7499,
        sale: true,
        bestSeller: false,
      },
    ],
  },
  {
    id: 8,
    category: "Jackets",
    products: [
      {
        name: "Urban Bomber Jacket",
        image: "https://example.com/images/jackets/bomber.jpg",
        description: "Zip-up jacket with modern edge.",
        price: 5499,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Denim Jacket",
        image: "https://example.com/images/jackets/denim.jpg",
        description: "Timeless rugged denim outerwear.",
        price: 5299,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Puffer Winter Jacket",
        image: "https://example.com/images/jackets/puffer.jpg",
        description: "Warm down-filled winter coat.",
        price: 6499,
        sale: true,
        bestSeller: false,
      },
    ],
  },
  {
    id: 9,
    category: "Hoodies",
    products: [
      {
        name: "Classic Pullover Hoodie",
        image: "https://example.com/images/hoodies/classic.jpg",
        description: "Soft fleece hoodie with kangaroo pocket.",
        price: 2999,
        sale: false,
        bestSeller: true,
      },
      {
        name: "Zip-Up Lightweight Hoodie",
        image: "https://example.com/images/hoodies/zip.jpg",
        description: "Perfect layering for mild days.",
        price: 2799,
        sale: true,
        bestSeller: false,
      },
      {
        name: "Graphic Streetwear Hoodie",
        image: "https://example.com/images/hoodies/graphic.jpg",
        description: "Bold print for urban style.",
        price: 3199,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 10,
    category: "Sweaters",
    products: [
      {
        name: "Cable-Knit Crew Sweater",
        image: "https://example.com/images/sweaters/cable.jpg",
        description: "Cozy cable knit in soft wool blend.",
        price: 3999,
        sale: false,
        bestSeller: true,
      },
      {
        name: "V-Neck Merino Sweater",
        image: "https://example.com/images/sweaters/merino.jpg",
        description: "Smart lightweight layering piece.",
        price: 3699,
        sale: true,
        bestSeller: false,
      },
      {
        name: "Quarter-Zip Pullover",
        image: "https://example.com/images/sweaters/zip.jpg",
        description: "Casual zip neck for comfort days.",
        price: 3899,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 11,
    category: "Ethnic Wear",
    products: [
      {
        name: "Embroidered Kurta Set",
        image: "https://example.com/images/ethnic/kurta1.jpg",
        description: "Festive kurta with intricate embroidery.",
        price: 4599,
        sale: false,
        bestSeller: true,
      },
      {
        name: "Silk Printed Kurta",
        image: "https://example.com/images/ethnic/kurta2.jpg",
        description: "Elegant silk print for celebrations.",
        price: 5299,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Cotton Pathani Kurta",
        image: "https://example.com/images/ethnic/kurta3.jpg",
        description: "Breathable cotton kurta for comfort.",
        price: 3999,
        sale: true,
        bestSeller: false,
      },
    ],
  },
  {
    id: 12,
    category: "Nehru Jackets",
    products: [
      {
        name: "Silk Nehru Jacket",
        image: "https://example.com/images/nehru/silk.jpg",
        description: "Formal silk jacket in classic cut.",
        price: 6199,
        sale: false,
        bestSeller: true,
      },
      {
        name: "Cotton Nehru Waistcoat",
        image: "https://example.com/images/nehru/cotton.jpg",
        description: "Lightweight and versatile waistcoat.",
        price: 4899,
        sale: true,
        bestSeller: false,
      },
      {
        name: "Velvet Nehru Jacket",
        image: "https://example.com/images/nehru/velvet.jpg",
        description: "Premium velvet ideal for weddings.",
        price: 6999,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 13,
    category: "Innerwear",
    products: [
      {
        name: "Cotton Boxers Pack",
        image: "https://example.com/images/innerwear/boxers.jpg",
        description: "Pack of 3 breathable cotton boxers.",
        price: 1199,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Seamless Vests",
        image: "https://example.com/images/innerwear/vests.jpg",
        description: "Soft seamless vests for daily wear.",
        price: 899,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Thermal Shorts",
        image: "https://example.com/images/innerwear/thermal.jpg",
        description: "Warm lightweight thermals.",
        price: 1499,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 14,
    category: "Sleepwear",
    products: [
      {
        name: "Cotton Pajama Set",
        image: "https://example.com/images/sleepwear/pajama.jpg",
        description: "Soft pajamas with relaxed fit.",
        price: 1799,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Silk Nightshirt",
        image: "https://example.com/images/sleepwear/nightshirt.jpg",
        description: "Luxurious silk nightshirt.",
        price: 2499,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Thermal Pyjama Set",
        image: "https://example.com/images/sleepwear/thermal.jpg",
        description: "Warm thermals for chilly nights.",
        price: 1999,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 15,
    category: "Footwear",
    products: [
      {
        name: "Casual Sneakers",
        image: "https://example.com/images/footwear/sneakers.jpg",
        description: "Everyday canvas sneakers.",
        price: 2499,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Leather Loafers",
        image: "https://example.com/images/footwear/loafers.jpg",
        description: "Smart formal loafers in leather.",
        price: 3999,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Sport Sandals",
        image: "https://example.com/images/footwear/sandals.jpg",
        description: "Comfortable sandals for outings.",
        price: 1999,
        sale: false,
        bestSeller: false,
      },
    ],
  },
  {
    id: 16,
    category: "Formal Wear",
    products: [
      {
        name: "Three-Piece Suit",
        image: "https://example.com/images/formal/suit.jpg",
        description: "Complete three-piece suit set.",
        price: 14999,
        sale: true,
        bestSeller: true,
      },
      {
        name: "Tailored Tuxedo",
        image: "https://example.com/images/formal/tuxedo.jpg",
        description: "Elegant tuxedo for black-tie events.",
        price: 17999,
        sale: false,
        bestSeller: false,
      },
      {
        name: "Formal Waistcoat",
        image: "https://example.com/images/formal/waistcoat.jpg",
        description: "Classic waistcoat to complement suits.",
        price: 4999,
        sale: false,
        bestSeller: false,
      },
    ],
  },
];

export { categoriesMan };
