import DenimJacket from "../assets/images/DenimJacket.jpg";
import FloralSummerDress from "../assets/images/FloralSummerDress.jpg";
import KidsCartoonHoodie from "../assets/images/KidsCartoonHoodie.jpg";
import MensCasualTshirt from "../assets/images/CasualTshirt.jpg";
import WomensWorkoutLeggings from "../assets/images/WomenWorkout.jpg";
import KidsRainbowDress from "../assets/images/RainbowDress.jpg";
import MensFormalShirt from "../assets/images/FormalShirt.jpg";
import WomensWinterCoat from "../assets/images/WinterCoat.jpg";
import KidsPajamaSet from "../assets/images/PajamaSet.jpg";
import MensSportsShorts from "../assets/images/SportsShort.jpg";

const productMenu = [
  {
    id: 1,
    name: "Denim Jacket",
    price: 2499,
    category: "Men",
    description: "A timeless denim jacket with durable stitching.",
    image: DenimJacket,
    discount: "10% OFF",
    discountPrice: 2249,
    bestSeller: true,
    // category_Image: CategoryMens,
  },
  {
    id: 2,
    name: "Floral Summer Dress",
    price: 1799,
    category: "Women",
    description: "Light and breezy floral dress perfect for summer days.",
    image: FloralSummerDress,
    discount: "15% OFF",
    discountPrice: 1524,
    bestSeller: false,
  },
  {
    id: 3,
    name: "Kids Cartoon Hoodie",
    price: 999,
    category: "Kids",
    description: "Cozy hoodie featuring a fun cartoon character.",
    image: KidsCartoonHoodie,
    discount: "5% OFF",
    discountPrice: 949,
    bestSeller: true,
  },
  {
    id: 4,
    name: "Men's Casual T-Shirt",
    price: 799,
    category: "Men",
    description: "Soft cotton t-shirt perfect for everyday wear.",
    image: MensCasualTshirt,
    discount: "20% OFF",
    discountPrice: 639,
    bestSeller: false,
  },
  {
    id: 5,
    name: "Women's Workout Leggings",
    price: 1199,
    category: "Women",
    description: "Stretchy and comfortable leggings for active use.",
    image: WomensWorkoutLeggings,
    discount: "10% OFF",
    discountPrice: 1079,
    bestSeller: true,
  },
  {
    id: 6,
    name: "Kids Rainbow Dress",
    price: 1099,
    category: "Kids",
    description: "Colorful dress for playful occasions.",
    image: KidsRainbowDress,
    discount: "5% OFF",
    discountPrice: 1044,
    bestSeller: false,
  },
  {
    id: 7,
    name: "Men's Formal Shirt",
    price: 1499,
    category: "Men",
    description: "Tailored fit shirt ideal for formal events.",
    image: MensFormalShirt,
    discount: "10% OFF",
    discountPrice: 1349,
    bestSeller: true,
  },
  {
    id: 8,
    name: "Women's Winter Coat",
    price: 3499,
    category: "Women",
    description: "Stylish and warm coat for winter days.",
    image: WomensWinterCoat,
    discount: "15% OFF",
    discountPrice: 2974,
    bestSeller: false,
  },
  {
    id: 9,
    name: "Kids Pajama Set",
    price: 799,
    category: "Kids",
    description: "Comfortable pajama set with fun prints.",
    image: KidsPajamaSet,
    discount: "5% OFF",
    discountPrice: 759,
    bestSeller: true,
  },
  {
    id: 10,
    name: "Men's Sports Shorts",
    price: 899,
    category: "Men",
    description: "Breathable sports shorts ideal for gym and running.",
    image: MensSportsShorts,
    discount: "10% OFF",
    discountPrice: 809,
    bestSeller: false,
  },
  {
    id: 11,
    name: "Floral Summer Dress",
    price: 1999,
    category: "Women",
    description: "Light and breezy floral dress perfect for summer days.",
    image: FloralSummerDress,
    discount: "15% OFF",
    discountPrice: 1524,
    bestSeller: false,
  },
  {
    id: 12,
    name: "Floral Summer Dress",
    price: 2199,
    category: "Women",
    description: "Light and breezy floral dress perfect for summer days.",
    image: FloralSummerDress,
    discount: "25% OFF",
    discountPrice: 1000,
    bestSeller: true,
  },
  {
    id: 13,
    name: "Kids Pajama Set",
    price: 799,
    category: "Kids",
    description: "Comfortable pajama set with fun prints.",
    image: KidsPajamaSet,
    discount: "10% OFF",
    discountPrice: 699,
    bestSeller: false,
  },
];
export { productMenu };
